# Site settings
title: 枫& zi
email: rw.ifeng#google.com
description: "no dangers no wonders"
baseurl: ""
url: "http://www.rwifeng.com"
username: "rwifeng"

# Build settings
markdown: kramdown
permalink: pretty
